### ISSUE TITLE
大神，运行监控采集脚本出现问题，问题已经解决

### ISSUE THREAD

**Issue by swingpon** [wuchanghui5220/pi-node-monitor#1]
运行环境检查：
Docker Desktop:   [ OK ]
Pi Network Node:  [ OK ]
Linux nmap:       [ OK ]
Linux dos2unix:   [ OK ]
nginx container:  [ None ]
检查未全部通过，程序退出！

请问这个问题怎么解决？

**Comment by wuchanghui5220** [comment]
在Docker 手动打开 nginx 容器，
